
import java.awt.Color;
import java.awt.Font;
import java.text.SimpleDateFormat;
import java.util.*;
import javax.swing.JOptionPane;
import javax.swing.JToggleButton;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Hrithik
 */
public class Bus_reservations extends javax.swing.JFrame {
    public static int select_bus=-1;
    /**
     * Creates new form Bus_reservations
     */
    public Bus_reservations() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox6.setSelected(true);
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox4.setSelected(true);
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox3.setSelected(true);
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox2.setSelected(true);
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox1.setSelected(true);
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox5.setSelected(true);
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        JTableHeader header2 = jTable1.getTableHeader();
        header2.setFont(new Font("Dialog", Font.BOLD, 20));
        header2.setForeground(Color.BLACK);
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel2.add(jLabel8);
        jLabel8.setBounds(930, 100, 290, 40);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back logo.png"))); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel10);
        jLabel10.setBounds(1280, 10, 50, 70);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel2.add(jLabel7);
        jLabel7.setBounds(540, 100, 330, 40);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel2.add(jLabel6);
        jLabel6.setBounds(140, 100, 330, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/book_reservation.png"))); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(0, -20, 1270, 200);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(123, 42, 255));
        jLabel2.setText("FILTERS");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(123, 42, 255));
        jLabel3.setText("DEPARTURE TIME");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(123, 42, 255));
        jLabel4.setText("AC TYPE");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(123, 42, 255));
        jLabel5.setText("SLEEPER TYPE");

        jCheckBox6.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox6.setText("SLEEPER");
        jCheckBox6.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox6ItemStateChanged(evt);
            }
        });

        jCheckBox4.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox4.setText("NON AC TYPE");
        jCheckBox4.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox4ItemStateChanged(evt);
            }
        });

        jCheckBox3.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox3.setText("AC TYPE");
        jCheckBox3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox3ItemStateChanged(evt);
            }
        });

        jCheckBox2.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox2.setText("12 PM - 12 AM");
        jCheckBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox2ItemStateChanged(evt);
            }
        });
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });

        jCheckBox1.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox1.setText("12 AM - 12 PM");
        jCheckBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox1ItemStateChanged(evt);
            }
        });

        jCheckBox5.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox5.setText("SEATER");
        jCheckBox5.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox5ItemStateChanged(evt);
            }
        });

        jComboBox1.setBackground(new java.awt.Color(123, 42, 255));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SORT BY", "DEPARTURE TIME", "PRICE - LOW TO HIGH", "PRICE - HIGH TO LOW" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "BUS NAME", "PRICE", "DEPARTURE", "ARRIVAL", "AC TYPE", "SEATER TYPE", "AVAILABLE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(123, 42, 255));
        jTable1.setRowHeight(35);
        jTable1.setSelectionBackground(new java.awt.Color(123, 42, 255));
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(140);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(140);
            jTable1.getColumnModel().getColumn(1).setMinWidth(140);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(140);
            jTable1.getColumnModel().getColumn(2).setMinWidth(140);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(140);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(140);
            jTable1.getColumnModel().getColumn(4).setMinWidth(140);
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(140);
            jTable1.getColumnModel().getColumn(5).setMinWidth(140);
            jTable1.getColumnModel().getColumn(5).setPreferredWidth(140);
            jTable1.getColumnModel().getColumn(6).setMinWidth(140);
            jTable1.getColumnModel().getColumn(6).setPreferredWidth(140);
        }

        jLabel9.setBackground(new java.awt.Color(123, 42, 255));
        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BOOK_SEATS.png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jCheckBox3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jCheckBox4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jCheckBox5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jCheckBox6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                            .addComponent(jCheckBox2)
                            .addComponent(jCheckBox1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(44, 44, 44)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1059, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(76, 76, 76))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(516, 516, 516)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBox1)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBox2)
                        .addGap(17, 17, 17)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBox3)
                        .addGap(11, 11, 11)
                        .addComponent(jCheckBox4)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel5)
                        .addGap(21, 21, 21)
                        .addComponent(jCheckBox5)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBox6))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(77, 77, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void filterandsorttable(){
        
        String sortby ="order by bname";
        DefaultTableModel model=(DefaultTableModel)Bus_reservations.jTable1.getModel();
        int rows=model.getRowCount();
        if(rows>0)
         {
             for(int i=0;i<rows;i++)
            {
                    model.removeRow(0);
            }
        }
        
        String date = jLabel8.getText();
        String source = jLabel6.getText();
        String destination = jLabel7.getText();

        int iac=0;
        int inac=0 ;//nonac
        int isl=0;
        int ist=0 ;
        int dawn=0 ;
        int dusk=0 ;
        
        int ind = jComboBox1.getSelectedIndex();
        
        if(ind == 1)
        {
            sortby = "order by dep_time";
        }
        else if(ind == 2)
        {
            sortby = "order by (base_fare + AC_fare + non_AC_fare + sl_fare + st_fare)";
        }
        else if(ind == 3)
        {
            sortby = "order by (base_fare + AC_fare + non_AC_fare + sl_fare + st_fare) desc";
        }
        if(jCheckBox1.isSelected())
        {
            dawn=1;
        }
        if(jCheckBox2.isSelected())
        {
            dusk=1;
        }
        if(jCheckBox3.isSelected())
        {
            iac=1;
        }
        if(jCheckBox4.isSelected())
        {
            inac=1;
        }
        if(jCheckBox5.isSelected())
        {
            ist=1;
        }
        if(jCheckBox6.isSelected())
        {
            isl=1;
        }
        String max = "";
        String min = "";

        if(iac == inac) {
            iac = 0;
            inac = 0;
        }
        else if(iac == 0) {
            iac = 10000;
            inac = 0;
        }
        else if(inac == 0) {
            inac = 10000;
            iac = 0;
        }
        if(isl == ist) {
            isl = 0;
            ist = 0;
        }
        else if(isl == 0) {
            isl = 10000;
            ist = 0;
        }
        else if(ist == 0) {
            ist = 10000;
            isl = 0;
        }
        if(dawn == dusk) {
            min = "00:00:00";
            max = "23:59:59";
        }
        else if(dusk == 0) {
            min = "00:00:00";
            max = "11:59:59";
        }
        else if(dawn == 0) {
            min = "12:00:00";
            max = "23:59:59";
        }

        boolean f =Filter.FilterinDB(source.toUpperCase(),destination.toUpperCase(),date,iac,inac,isl,ist,min,max,sortby);
        
        if(f)
        {
            for(int i=0;i<Selection.length;i++)
            {
                String acb,sleep;
                if(Selection.ac[i]==1)
                {
                    acb ="AC";
                }
                else
                {
                    acb ="NON-AC";
                }
                if(Selection.sl[i]==1)
                {
                    sleep ="Sleeper";
                }
                else
                {
                    sleep ="Seater";
                }
                model.addRow(new Object[] {Selection.names[i],Selection.fare[i],Selection.dep_times[i],Selection.dest_times[i],acb,sleep,Selection.available[i]});
            }
        }
    
    }
    
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        
        DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
        jTable1.setRowSelectionAllowed(true);
        try
        {
            int row=jTable1.getSelectedRow();
            int bus_id = Selection.numbers[row];
            select_bus=row;
            String seater = model.getValueAt(row,5).toString();

            String date_s = jLabel8.getText(); 
            SimpleDateFormat dt = new SimpleDateFormat("dd/MM/yyyy"); 
            Date date = null; 
            try {
                date = dt.parse(date_s);
            } catch (Exception e) {
                System.out.println(e);
            }
            SimpleDateFormat dt1 = new SimpleDateFormat("yyyy-MM-dd");

            Book_seats.selectedBus(bus_id,dt1.format(date));


            if(seater.equals("Seater"))
            {
                new seat_reservation().setVisible(true);

                JToggleButton button[] = new JToggleButton[]{seat_reservation.jToggleButton1,seat_reservation.jToggleButton2,seat_reservation.jToggleButton3
                ,seat_reservation.jToggleButton4,seat_reservation.jToggleButton5,seat_reservation.jToggleButton6
                ,seat_reservation.jToggleButton7,seat_reservation.jToggleButton8,seat_reservation.jToggleButton9
                ,seat_reservation.jToggleButton10,seat_reservation.jToggleButton11,seat_reservation.jToggleButton12
                ,seat_reservation.jToggleButton13,seat_reservation.jToggleButton14,seat_reservation.jToggleButton15
                ,seat_reservation.jToggleButton16,seat_reservation.jToggleButton17,seat_reservation.jToggleButton18
                ,seat_reservation.jToggleButton19,seat_reservation.jToggleButton22,seat_reservation.jToggleButton21};



                for(int i =0;i<button.length;i++)
                {
                    for(int j =0;j<Book_seats.length;j++)
                    {
                        if(i+1==Book_seats.bookedseats[j])
                        {
                            JToggleButton b = button[i];
                             b.setEnabled(false);
                            break;
                        }
                    }
                }
                seat_reservation.jLabel8.setText(jLabel8.getText());
                seat_reservation.jLabel10.setText(jLabel6.getText());
                seat_reservation.jLabel11.setText(jLabel7.getText());
                seat_reservation.jLabel3.setText(model.getValueAt(jTable1.getSelectedRow(), 0).toString()+" "+model.getValueAt(jTable1.getSelectedRow(), 4).toString());
                seat_reservation.jLabel4.setText(model.getValueAt(jTable1.getSelectedRow(), 2).toString()); 
                seat_reservation.jLabel5.setText(model.getValueAt(jTable1.getSelectedRow(), 3).toString());


                this.setVisible(false);
            }
            else
            {
                new Sleeper_reservation().setVisible(true);

                JToggleButton button[] = new JToggleButton[]{Sleeper_reservation.jToggleButton1,Sleeper_reservation.jToggleButton2,Sleeper_reservation.jToggleButton3
                ,Sleeper_reservation.jToggleButton4,Sleeper_reservation.jToggleButton5,Sleeper_reservation.jToggleButton6
                ,Sleeper_reservation.jToggleButton7,Sleeper_reservation.jToggleButton8,Sleeper_reservation.jToggleButton9
                ,Sleeper_reservation.jToggleButton10,Sleeper_reservation.jToggleButton11,Sleeper_reservation.jToggleButton12};



                for(int i =0;i<button.length;i++)
                {
                    for(int j =0;j<Book_seats.length;j++)
                    {
                        if(i+1==Book_seats.bookedseats[j])
                        {
                            button[i].setEnabled(false);
                            break;
                        }
                    }
                }

                Sleeper_reservation.jLabel12.setText(jLabel8.getText());
                Sleeper_reservation.jLabel14.setText(jLabel6.getText());
                Sleeper_reservation.jLabel13.setText(jLabel7.getText());
                Sleeper_reservation.jLabel3.setText(model.getValueAt(jTable1.getSelectedRow(), 0).toString()+" "+model.getValueAt(jTable1.getSelectedRow(), 4).toString());
                Sleeper_reservation.jLabel4.setText(model.getValueAt(jTable1.getSelectedRow(), 2).toString()); 
                Sleeper_reservation.jLabel5.setText(model.getValueAt(jTable1.getSelectedRow(), 3).toString());
                this.setVisible(false);

            }
        }
        catch (Exception e)
        {
             JOptionPane.showMessageDialog(this, "Please select a Bus to Proceed!");
        }
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        new homepage().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jCheckBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox1ItemStateChanged
        // TODO add your handling code here:
        filterandsorttable();
    }//GEN-LAST:event_jCheckBox1ItemStateChanged

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jCheckBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox2ItemStateChanged
        // TODO add your handling code here:
        filterandsorttable();
    }//GEN-LAST:event_jCheckBox2ItemStateChanged

    private void jCheckBox3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox3ItemStateChanged
        // TODO add your handling code here:
        filterandsorttable();
    }//GEN-LAST:event_jCheckBox3ItemStateChanged

    private void jCheckBox4ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox4ItemStateChanged
        // TODO add your handling code here:
        filterandsorttable();
    }//GEN-LAST:event_jCheckBox4ItemStateChanged

    private void jCheckBox5ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox5ItemStateChanged
        // TODO add your handling code here:
        filterandsorttable();
    }//GEN-LAST:event_jCheckBox5ItemStateChanged

    private void jCheckBox6ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox6ItemStateChanged
        // TODO add your handling code here:
        filterandsorttable();
    }//GEN-LAST:event_jCheckBox6ItemStateChanged

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        // TODO add your handling code here:
        filterandsorttable();
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bus_reservations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bus_reservations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bus_reservations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bus_reservations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bus_reservations().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public static javax.swing.JLabel jLabel6;
    public static javax.swing.JLabel jLabel7;
    public static javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
