
import java.awt.Color;
import java.awt.Font;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JToggleButton;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Hrithik
 */
public class Sleeper_reservation extends javax.swing.JFrame {
    public int seat_selected=0;
    /**
     * Creates new form Sleeper_reservation
     */
    public Sleeper_reservation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jToggleButton5 = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton6 = new javax.swing.JToggleButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton7 = new javax.swing.JToggleButton();
        jToggleButton8 = new javax.swing.JToggleButton();
        jToggleButton9 = new javax.swing.JToggleButton();
        jToggleButton10 = new javax.swing.JToggleButton();
        jToggleButton11 = new javax.swing.JToggleButton();
        jToggleButton12 = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        JTableHeader header2 = jTable1.getTableHeader();
        header2.setFont(new Font("Dialog", Font.BOLD, 20));
        header2.setForeground(Color.BLACK);
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jCheckBox2 = new javax.swing.JCheckBox();

        jCheckBox1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox1.setText("Confirm your Booking Details");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back logo.png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel9);
        jLabel9.setBounds(1320, 10, 50, 70);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel2.add(jLabel12);
        jLabel12.setBounds(930, 110, 300, 40);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel2.add(jLabel14);
        jLabel14.setBounds(140, 110, 330, 40);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel2.add(jLabel13);
        jLabel13.setBounds(530, 110, 340, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/book_reservation.png"))); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(0, 0, 1400, 170);

        jToggleButton5.setBackground(new java.awt.Color(255, 255, 255));
        jToggleButton5.setText("5");
        jToggleButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jToggleButton5);
        jToggleButton5.setBounds(57, 491, 50, 90);

        jToggleButton4.setBackground(new java.awt.Color(255, 255, 255));
        jToggleButton4.setText("4");
        jToggleButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jToggleButton4);
        jToggleButton4.setBounds(315, 361, 50, 97);

        jToggleButton3.setBackground(new java.awt.Color(255, 255, 255));
        jToggleButton3.setText("3");
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jToggleButton3);
        jToggleButton3.setBounds(247, 361, 50, 93);

        jToggleButton2.setBackground(new java.awt.Color(255, 255, 255));
        jToggleButton2.setText("2");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jToggleButton2);
        jToggleButton2.setBounds(125, 362, 50, 96);

        jToggleButton6.setBackground(new java.awt.Color(255, 255, 255));
        jToggleButton6.setText("6");
        jToggleButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jToggleButton6);
        jToggleButton6.setBounds(125, 491, 50, 90);

        jToggleButton1.setBackground(new java.awt.Color(255, 255, 255));
        jToggleButton1.setText("1");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jToggleButton1);
        jToggleButton1.setBounds(57, 361, 50, 97);

        jToggleButton7.setBackground(new java.awt.Color(255, 255, 255));
        jToggleButton7.setText("7");
        jToggleButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton7ActionPerformed(evt);
            }
        });
        jPanel2.add(jToggleButton7);
        jToggleButton7.setBounds(247, 491, 50, 90);

        jToggleButton8.setBackground(new java.awt.Color(255, 255, 255));
        jToggleButton8.setText("8");
        jToggleButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton8ActionPerformed(evt);
            }
        });
        jPanel2.add(jToggleButton8);
        jToggleButton8.setBounds(315, 491, 50, 90);

        jToggleButton9.setBackground(new java.awt.Color(255, 255, 255));
        jToggleButton9.setText("9");
        jToggleButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton9ActionPerformed(evt);
            }
        });
        jPanel2.add(jToggleButton9);
        jToggleButton9.setBounds(57, 617, 50, 82);

        jToggleButton10.setBackground(new java.awt.Color(255, 255, 255));
        jToggleButton10.setText("10");
        jToggleButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton10ActionPerformed(evt);
            }
        });
        jPanel2.add(jToggleButton10);
        jToggleButton10.setBounds(125, 617, 50, 82);

        jToggleButton11.setBackground(new java.awt.Color(255, 255, 255));
        jToggleButton11.setText("11");
        jToggleButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton11ActionPerformed(evt);
            }
        });
        jPanel2.add(jToggleButton11);
        jToggleButton11.setBounds(247, 617, 50, 82);

        jToggleButton12.setBackground(new java.awt.Color(255, 255, 255));
        jToggleButton12.setText("12");
        jToggleButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton12ActionPerformed(evt);
            }
        });
        jPanel2.add(jToggleButton12);
        jToggleButton12.setBounds(315, 617, 50, 82);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hrithik\\OneDrive\\Desktop\\dbms_project_pics\\STERRING.png")); // NOI18N
        jPanel2.add(jLabel2);
        jLabel2.setBounds(321, 315, 44, 39);

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PASSENGER NAME", "AGE", "GENDER(M/F)", "SEAT NO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setToolTipText("");
        jTable1.setGridColor(new java.awt.Color(123, 42, 255));
        jTable1.setRowHeight(30);
        jTable1.setSelectionBackground(new java.awt.Color(123, 42, 255));
        jTable1.setUpdateSelectionOnSort(false);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(140);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(140);
        }

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(519, 346, 769, 353);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel2.add(jLabel3);
        jLabel3.setBounds(57, 205, 308, 60);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel2.add(jLabel4);
        jLabel4.setBounds(560, 195, 146, 70);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel2.add(jLabel5);
        jLabel5.setBounds(1055, 188, 146, 77);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BOOKNOW.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel6);
        jLabel6.setBounds(780, 740, 171, 49);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bus arrow.png"))); // NOI18N
        jPanel2.add(jLabel7);
        jLabel7.setBounds(713, 200, 324, 65);

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hrithik\\OneDrive\\Desktop\\dbms_project_pics\\STERRING.png")); // NOI18N
        jPanel2.add(jLabel8);
        jLabel8.setBounds(131, 315, 44, 39);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("LOWER ");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(85, 726, 72, 27);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("UPPER");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(276, 726, 61, 27);

        jCheckBox2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox2.setText("Confirm your Booking Details");
        jPanel2.add(jCheckBox2);
        jCheckBox2.setBounds(510, 710, 220, 25);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1406, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 827, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void Select(JToggleButton b)
    {
        System.out.println("called \n");
        DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
        if(b.isSelected())
        {
            if(seat_selected<4)
            {
                String seat = b.getText();
                b.setBackground(Color.GREEN);
                seat_selected++;
                model.addRow(new Object[] {null,null,null,seat});
            }
            else
            {
                b.setSelected(false);
                b.setBackground(Color.WHITE);
                JOptionPane.showMessageDialog(this,"Maximum number of Seats Selection : 4");
               
            }
        }
        else
        {
            b.setBackground(Color.WHITE);
            seat_selected--;
            String seat = b.getText();
            int rows = model.getRowCount();
            for(int i =0;i<rows;i++)
            {
                if(model.getValueAt(i,3).equals(seat))
                {
                    model.removeRow(i);
                    break;
                }
            }
        }
        
    }
    private void jToggleButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton5ActionPerformed
        // TODO add your handling code here:
        Select(jToggleButton5);
    }//GEN-LAST:event_jToggleButton5ActionPerformed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
        // TODO add your handling code here:
        Select(jToggleButton3);
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here:
        Select(jToggleButton2);
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jToggleButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton7ActionPerformed
        // TODO add your handling code here:
        Select(jToggleButton7);
    }//GEN-LAST:event_jToggleButton7ActionPerformed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        new homepage().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        Select(jToggleButton1);
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton4ActionPerformed
        // TODO add your handling code here:
        Select(jToggleButton4);
    }//GEN-LAST:event_jToggleButton4ActionPerformed

    private void jToggleButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton6ActionPerformed
        // TODO add your handling code here:
        Select(jToggleButton6);
    }//GEN-LAST:event_jToggleButton6ActionPerformed

    private void jToggleButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton8ActionPerformed
        // TODO add your handling code here:
        Select(jToggleButton8);
    }//GEN-LAST:event_jToggleButton8ActionPerformed

    private void jToggleButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton9ActionPerformed
        // TODO add your handling code here:
        Select(jToggleButton9);
    }//GEN-LAST:event_jToggleButton9ActionPerformed

    private void jToggleButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton10ActionPerformed
        // TODO add your handling code here:
        Select(jToggleButton10);
    }//GEN-LAST:event_jToggleButton10ActionPerformed

    private void jToggleButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton11ActionPerformed
        // TODO add your handling code here:
        Select(jToggleButton11);
    }//GEN-LAST:event_jToggleButton11ActionPerformed

    private void jToggleButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton12ActionPerformed
        // TODO add your handling code here:
        Select(jToggleButton12);
    }//GEN-LAST:event_jToggleButton12ActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        if(jCheckBox2.isSelected())
        {
            boolean flag = true;
            String name,G;
            String age;
            int s;
            DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
            int rows  = model.getRowCount();
            int i=0;
            for( i =0;i<rows;i++)
            {
                name = model.getValueAt(i, 0).toString();
                age= model.getValueAt(i, 1).toString();
                G= model.getValueAt(i, 2).toString();
                if(!(Passenger_insertion.validate_age(age) && Passenger_insertion.validate_gender(G)&&Passenger_insertion.validate_username(name)))
                {
                    flag=false;
                    JOptionPane.showMessageDialog(this,"Invalid Entries found");
                    break; 
                }
            }
            if(i==rows && flag)
            {
                String date_s = jLabel12.getText(); 
                SimpleDateFormat dt = new SimpleDateFormat("dd/MM/yyyy"); 
                Date date = null; 
                try 
                {
                  date = dt.parse(date_s);
                } catch (Exception e) {
                    System.out.println(e);
                }
                SimpleDateFormat dt1 = new SimpleDateFormat("yyyy-MM-dd");
                Passenger_insertion.insertintoBooking(dt1.format(date),rows,Selection.numbers[Bus_reservations.select_bus]);
                for( i =0;i<rows;i++)
                {
                    name = model.getValueAt(i, 0).toString();
                    age= model.getValueAt(i, 1).toString();
                    G=model.getValueAt(i, 2).toString();
                    s=Integer.parseInt(model.getValueAt(i, 3).toString());
                    Passenger_insertion.insertintoDB(name,Integer.parseInt(age),G.toUpperCase(),s,Selection.fare[Bus_reservations.select_bus]);
                }
                
                Passenger_insertion.ticket_details();
                this.setVisible(false);
            }
            
        }
        else{
            JOptionPane.showMessageDialog(this,"Please confirm your Details");
        }
    }//GEN-LAST:event_jLabel6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sleeper_reservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sleeper_reservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sleeper_reservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sleeper_reservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sleeper_reservation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    public static javax.swing.JLabel jLabel12;
    public static javax.swing.JLabel jLabel13;
    public static javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    public static javax.swing.JLabel jLabel3;
    public static javax.swing.JLabel jLabel4;
    public static javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    public static javax.swing.JToggleButton jToggleButton1;
    public static javax.swing.JToggleButton jToggleButton10;
    public static javax.swing.JToggleButton jToggleButton11;
    public static javax.swing.JToggleButton jToggleButton12;
    public static javax.swing.JToggleButton jToggleButton2;
    public static javax.swing.JToggleButton jToggleButton3;
    public static javax.swing.JToggleButton jToggleButton4;
    public static javax.swing.JToggleButton jToggleButton5;
    public static javax.swing.JToggleButton jToggleButton6;
    public static javax.swing.JToggleButton jToggleButton7;
    public static javax.swing.JToggleButton jToggleButton8;
    public static javax.swing.JToggleButton jToggleButton9;
    // End of variables declaration//GEN-END:variables
}
